language: python
python:
  - "3.8"

before_install:
  - pip install poetry
  - poetry shell
# command to install dependencies
install:
  - poetry install
# command to run tests
script:
  - poetry run pycodestyle .
  - poetry run pytest