language: python
python:
  - "3.8"

before_install:
  - pip install poetry
# command to install dependencies
install:
  - poetry install -v
# command to run tests
script:
  - poetry run pycodestyle .
  - poetry run pytest